.TH "File" 3 "Fri Oct 12 2018" "cag" \" -*- nroff -*-
.ad l
.nh
.SH NAME
File
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFile\fP (string path='')"
.br
.RI "Constructor\&. "
.ti -1c
.RI "string \fBRead\fP ()"
.br
.ti -1c
.RI "bool \fBWrite\fP (string to_file)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "File::File (string path = \fC''\fP)\fC [explicit]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "string File::Read ()"
Read a file and returns a string 
.PP
\fBReturns:\fP
.RS 4
readed string 
.RE
.PP
< result of reading
.PP
< readed line 
.SS "bool File::Write (string to_file)"

.PP
\fBParameters:\fP
.RS 4
\fIto_file\fP this string will written to a file instead of old content 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for cag from the source code\&.
