.TH "Path" 3 "Sun Dec 16 2018" "cag" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Path
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPath\fP ()"
.br
.RI "default constructor "
.ti -1c
.RI "\fBPath\fP (const string &path_str)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBPath\fP (const \fBPath\fP &other)"
.br
.RI "A copy constructor\&. "
.ti -1c
.RI "\fBPath\fP & \fBoperator=\fP (const \fBPath\fP &other)"
.br
.ti -1c
.RI "\fBPath\fP & \fBoperator=\fP (const string &other)"
.br
.ti -1c
.RI "\fBStrext\fP \fBget_string\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &out, const \fBPath\fP &p)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Path::Path (const string & path_str)\fC [explicit]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath_str\fP 
.RE
.PP

.SS "Path::Path (const \fBPath\fP & other)"

.PP
A copy constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIother\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for cag from the source code\&.
