.TH "LoopContainer< T >" 3 "Sun Dec 16 2018" "cag" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoopContainer< T >
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoopContainer\fP (int size)"
.br
.ti -1c
.RI "void \fBadd\fP (T newone)"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.ti -1c
.RI "T & \fBget\fP (int val)"
.br
.ti -1c
.RI "void \fBreturn_cursor\fP ()"
.br
.ti -1c
.RI "void \fBset_cursor\fP (int new_pos)"
.br
.ti -1c
.RI "void \fBshift_r\fP (int n_times=1)"
.br
.ti -1c
.RI "void \fBshift_l\fP (int n_times=1)"
.br
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cag from the source code\&.
