.TH "LoopContainer< T >::iterator" 3 "Sun Dec 16 2018" "cag" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoopContainer< T >::iterator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator\fP (int val, \fBLoopContainer\fP &lc_ref)"
.br
.ti -1c
.RI "T \fBoperator*\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP \fBoperator++\fP ()"
.br
.ti -1c
.RI "const \fBiterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &other)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &other)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cag from the source code\&.
