.TH "Strext" 3 "Sun Dec 16 2018" "cag" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Strext
.SH SYNOPSIS
.br
.PP
.PP
Inherits string\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStrext\fP (string in)"
.br
.ti -1c
.RI "void \fBfind_and_replace\fP (string const &find, string const &replace)"
.br
.ti -1c
.RI "void \fBltrim\fP (const char *t)"
.br
.ti -1c
.RI "void \fBrtrim\fP (const char *t)"
.br
.ti -1c
.RI "void \fBtrim\fP (const char *t)"
.br
.ti -1c
.RI "void \fBsearch_all\fP (const string &to_find)"
.br
.ti -1c
.RI "set< uint64_t > & \fBget_searched_pos\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cag from the source code\&.
